FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y build-essential clang cmake && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN cmake -B build -DCMAKE_BUILD_TYPE=Release && \
    cmake --build build --config Release

CMD ["./build/m-Harness"]